#!/bin/bash
# ModSecurity 克隆/子模块相关环境变量默认值（由 modsecurity_clone.sh 最先加载）

MODSECURITY_GIT_URL="${MODSECURITY_GIT_URL:-}"
MODSECURITY_GITEE_URL="${MODSECURITY_GITEE_URL:-https://gitee.com/mirrors/ModSecurity.git}"
MODSECURITY_GITEE_LIBINJECTION_URL="${MODSECURITY_GITEE_LIBINJECTION_URL:-https://gitee.com/mirrors/libinjection.git}"
MODSECURITY_GITEE_MBEDTLS_URL="${MODSECURITY_GITEE_MBEDTLS_URL:-https://gitee.com/mirrors/mbedtls.git}"
MODSECURITY_GITEE_SECRULES_URL="${MODSECURITY_GITEE_SECRULES_URL:-https://gitee.com/mirrors/secrules-language-tests.git}"
MODSECURITY_GITEE_PYTHON_BINDINGS_URL="${MODSECURITY_GITEE_PYTHON_BINDINGS_URL:-https://gitee.com/mirrors/ModSecurity-Python-bindings.git}"
MODSECURITY_USE_GITEE_SUBMODULES="${MODSECURITY_USE_GITEE_SUBMODULES:-0}"
MODSECURITY_UPSTREAM_LIBINJECTION_URL="${MODSECURITY_UPSTREAM_LIBINJECTION_URL:-https://github.com/libinjection/libinjection.git}"
MODSECURITY_UPSTREAM_MBEDTLS_URL="${MODSECURITY_UPSTREAM_MBEDTLS_URL:-https://github.com/Mbed-TLS/mbedtls.git}"
MODSECURITY_GIT_CLONE_QUIET="${MODSECURITY_GIT_CLONE_QUIET:-0}"
MODSECURITY_OTHERS_SUBMODULES_GITEE_FIRST="${MODSECURITY_OTHERS_SUBMODULES_GITEE_FIRST:-0}"
